import java.util.Arrays;
import java.util.List;
import java.util.Random;

public class AnimalList {


    public List<String> getNames() {
        return names;
    }

    public List<String> getAnimals() {
        return animals;
    }

    private List<String> names = Arrays.asList( "Liam","Emma",
       "Noah","Olivia",
       "William",	"Ava",
       "James","Isabella",
       "Oliver", "Sophia",
       "Benjamin","Charlotte","Elijah",	"Mia",
       "Lucas","Amelia",
       "Mason",	"Harper",
       "Logan",	"Evely",
       "Alexander",	"Abigail",
       "Ethan",	"Emily",
       "Jacob",	"Elizabeth",
       "Michael",	"Mila",
       "Daniel",	"Ella",
       "Henry",	"Avery",
       "Jackson",	"Sofia",
       "Sebastian",	"Camila",
       "Aiden",	"Aria",
       "Matthew",	"Scarlett",
       "Samuel","Victoria",
       "David",	"Madison",
       "Joseph",	"Luna",
       "Carter",	"Grace",
       "Owen",	"Chloe",
       "Wyatt",	"Penelope",
       "John",	"Layla",
       "Jack",	"Riley",
       "Luke",	"Zoey",
       "Jayden",	"Nora",
       "Dylan",	"Lily",
       "Grayson",	"Eleanor",
       "Levi",	"Hannah",
       "Isaac",	"Lillian",
       "Gabriel",	"Addison",
       "Julian",	"Aubrey",
       "Mateo",	"Ellie",
       "Anthony",	"Stella", "Jaxon",	"Natalie",
       "Lincoln","Zoe",
       "Joshua",	"Leah",
       "Chris",	"Hazel",
       "Andrew",	"Violet",
       "Theodore",	"Aurora",
       "Caleb",	"Savannah",
       "Ryan",	"Audrey",
       "Asher",	"Brooklyn",
       "Nathan",	"Bella",
       "Thomas",	"Claire",
        	"Leo",	"Skylar",
       "Isaiah",	"Lucy",
       "Charles",	"Paisley",
       "Josiah",	"Everly",
       "Hudson",	"Anna",
       "Christian",	"Caroline",
       "Hunter",	"Nova",
       "Connor",	"Genesis",
       "Eli",	"Emilia",
       "Ezra",	"Kennedy",
       "Aaron",	"Samantha",
       "Landon",	"Maya",
       "Adrian",	"Willow",
       "Jonathan",	"Kinsley",
       "Nolan",	"Naomi",
       "Jeremiah",	"Aaliyah",
       "Easton",	"Elena",
       "Elias",	"Sarah",
       "Colton",	"Ariana",
       "Cameron",	"Allison",
       "Carson",	"Gabriella",
       "Robert",	"Alice",
       "Angel",	"Madelyn",
       "Maverick",	"Cora",
       "Nicholas",	"Ruby",
       "Dominic",	"Eva",
       "Jaxson",	"Serenity",
       "Greyson",	"Autumn",
       "Adam",	"Adeline",
       "Ian",	"Hailey",
       "Austin",	"Gianna",
       "Santiago",	"Valentina",
       "Jordan",	"Isla",
       "Cooper",	"Eliana",
       "Brayden",	"Quinn",
       "Roman",	"Nevaeh",
       "Evan",	"Ivy",
       "Ezekiel",	"Sadie",
       "Xavier",	"Piper",
       "Jose",	"Lydia",
       "Jace",	"Alexa",
       "Jameson",	"Josephine",
       "Leonardo",	"Emery",
       "Bryson","Julia",
       "Axel",	"Delilah",
       "Everett",	"Arianna",
       "Parker",	"Vivian",
       "Kayden",	"Kaylee",
       "Miles",	"Sophie",
       "Sawyer",	"Brielle",
       "Jason",	"Madeline");

    private List<String> animals = Arrays.asList(
        "Squirrel",
        "Cougar",
        "Raven",
        "Cat",
        "Alligator",
        "Possum",
        "Lion",
        "Crocodile",
        "Brown Bear",
        "Koala",
        "Tiger",
        "Chipmunks",
        "Bear",
        "Swan",
        "Rabbit",
        "Whale",
        "Platypus",
        "Goat",
        "Duck",
        "Octopus",
        "Sheep",
        "Zebra",
        "Anaconda",
        "Cow",
        "Goose",
        "Bald Eagle",
        "Pig",
        "Donkey",
        "Osprey",
        "Parrot",
            "Panda",
            "Poodle",
            "Bear",
            "Elephant",
            "Skunk",
            "Bull",
            "Dolphin",
            "Jaguar",
            "Rooster",
            "Salamander",
            "Tortoise",
            "Chicken",
            "Raccoon",
            "Hedgehog",
            "Piranha",
            "Penguin",
            "Iguana",
            "Turkey",
            "Polar Bear",
            "Flamingo",
            "Crow",
            "Walrus",
            "Worm",
            "Ape",
            "Jellyﬁsh",
            "Frog",
            "Monkey",
            "Giraffe",
            "Sloth",
            "Pigeon",
            "Ostrich",
            "Lobster",
            "Tuna",
            "Wolf",
            "Swordﬁsh",
            "Cod",
            "Deer",
            "Mackerel",
            "Gecko",
            "Antelope",
            "Bonito",
            "Spider",
            "Catﬁsh",
            "Trout",
            "Cobra",
            "Whale",
            "Falcon",
            "Hamster",
            "Fox",
            "Chimpanzee",
            "Seal",
            "Lama",
            "Kangaroo",
            "Leopard",
            "Camel",
            "Porcupines",
            "Cheetah",
            "Gorilla",
            "Hyena",
            "Crab",
            "Toad",
            "Hippo",
            "Mouse ",
            "Quail ",
            "Rhino",
            "Rat",
            "Moose",
            "Crab");
}
